version: '3'
services:
  front:
    image: nginx:alpine
    container_name: front-web
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
